---
  - hosts: nodes
    become: yes
    become_user: root
    remote_user: centos

    tasks:
      - name: Synchronization
        copy:
          src: netology/
          dest: "/opt/netology/"
          owner: root
          group: root
          mode: 0644
        become: true
